In [1]:
import pandas as pd
from functions.myfunctions import read_json_column

In [2]:
vdjdb = pd.read_csv('data/vdj_cleaned_subset_for_MI_no-small-study.csv', index_col=0)
tcrdb = pd.read_csv('data/tcrdb_export_cleaned_withseqs.csv', index_col=0).drop_duplicates(subset = ['pdb'], keep='first')
tcrdb_bound = pd.read_csv('data/tcrdbset_unique_receptors_bound.csv', index_col=0).drop_duplicates(subset = ['pdb'], keep='first')
tcrdb_unbound = pd.read_csv('data/tcrdbset_unique_receptors_unbound.csv', index_col=0)

In [3]:
non_redudant_bound_pdbs = [x[0].strip('[] \'') for x in tcrdb_bound['pdb'].str.split(',')]
non_redudant_unbound_pdbs = [x[0].strip('[] \'') for x in tcrdb_unbound['pdb'].str.split(',')]

In [4]:
len(non_redudant_bound_pdbs), len(non_redudant_unbound_pdbs)

(157, 78)

In [5]:
tcrdb.shape, vdjdb.shape

((340, 41), (9713, 37))

In [6]:
tcrdb_bound.shape

(157, 40)

In [7]:
vdjdb['structure'] = read_json_column(vdjdb, 'Meta', 'structure.id').fillna('nope')
vdjdb['structure'].value_counts()

nope    9712
5EUO       1
Name: structure, dtype: int64

In [8]:
structures_in_filtered_vdjdb = vdjdb.loc[vdjdb['structure'] != 'nope']['structure'].str.lower().tolist()
structures_in_filtered_vdjdb

['5euo']

In [9]:
tcrdb.loc[tcrdb['pdb'].str.lower().isin(structures_in_filtered_vdjdb)]

,pdb,Bchain,Achain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,...,affinity_pmid,engineered,alpha_aa_imgt,alpha_aa_imgt_withGaps,beta_aa_imgt,beta_aa_imgt_withGaps,epitope_aa,bound,alpha_aa_imgt_shorter,beta_aa_imgt_shorter
0,5euo,H,G,abTCR,0,I,peptide,matrix protein 1,NaN,MH1,...,NaN,True,TQLLEQSPQFLSIQEGENLTVYCNSSSVFSSLQWYRQEPGEGPVLL...,TQLLEQSPQFLSIQEGENLTVYCNSSSVF-------SSLQWYRQEP...,GITQSPKYLFRKEGQNVTLSCEQNLNHDAMYWYRQDPGQGLRLIYY...,--GITQSPKYLFRKEGQNVTLSCEQNLNH-------DAMYWYRQDP...,GILGFVFTL,True,TQLLEQSPQFLSIQEGENLTVYCNSSSVFSSLQWYRQEPGEGPVLL...,GITQSPKYLFRKEGQNVTLSCEQNLNHDAMYWYRQDPGQGLRLIYY...

In [10]:
epitopes_in_structures = tcrdb['epitope_aa'].unique().tolist()
epitopes_in_vdjdb = vdjdb['Epitope'].unique().tolist()

In [11]:
set(epitopes_in_structures) & set(epitopes_in_vdjdb)

{'ASNENMETM',
 'ELAGIGILTV',
 'GILGFVFTL',
 'GLCTLVAML',
 'NLVPMVATV',
 'SSLENFRAYV',
 'YLQPRTFLL'}

In [12]:
tcrdb

,pdb,Bchain,Achain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,...,affinity_pmid,engineered,alpha_aa_imgt,alpha_aa_imgt_withGaps,beta_aa_imgt,beta_aa_imgt_withGaps,epitope_aa,bound,alpha_aa_imgt_shorter,beta_aa_imgt_shorter
0,1ao7,E,D,abTCR,0,C,peptide,tax peptide,NaN,MH1,...,NaN,True,KEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPELI...,-KEVEQNSGPLSVPEGAIASLNCTYSDRG------SQSFFWYRQYS...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNH-------EYMSWYRQDP...,LLFGYPVYV,True,KEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPELI...,GVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLIHY...
0,1bd2,E,D,abTCR,0,C,peptide,tax peptide,NaN,MH1,...,NaN,True,QQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFL...,-QQVKQNSPSLSVQEGRISILNCDYTNSM------FDYFLWYKKYP...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNH-------EYMSWYRQDP...,LLFGYPVYV,True,QQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...
0,1d9k,F,E,abTCR,0,Q,peptide,conalbumin peptide,NaN,MH2,...,NaN,True,QVRQSPQSLTVWEGETTILNCSYEDSTFDYFPWYRQFPGKSPALLI...,--QVRQSPQSLTVWEGETTILNCSYEDST------FDYFPWYRQFP...,AVTQSPRNKVAVTGGKVTLSCNQTNNHNNMYWYRQDTGHGLRLIHY...,--AVTQSPRNKVAVTGGKVTLSCNQTNNH-------NNMYWYRQDT...,GNSHRGAIEWEGIESG,True,QVRQSPQSLTVWEGETTILNCSYEDSTFDYFPWYRQFPGKSPALLI...,AVTQSPRNKVAVTGGKVTLSCNQTNNHNNMYWYRQDTGHGLRLIHY...
0,1fo0,B,A,abTCR,0,P,peptide,naturally processed octapeptide pbm1,NaN,MH1,...,NaN,True,QKVTQTQTSISVMEKTTVTMDCVYETQDSSYFLFWYKQTASGEIVF...,-QKVTQTQTSISVMEKTTVTMDCVYETQDS-----SYFLFWYKQTA...,VTLLEQNPRWRLVPRGQAVNLRCILKNSQYPWMSWYQQDLQKQLQW...,VTLLEQNPRWRLVPRGQAVNLRCILKNSQ------YPWMSWYQQDL...,INFDFNTI,True,QKVTQTQTSISVMEKTTVTMDCVYETQDSSYFLFWYKQTASGEIVF...,VTLLEQNPRWRLVPRGQAVNLRCILKNSQYPWMSWYQQDLQKQLQW...
0,1fyt,E,D,abTCR,0,C,peptide,hemagglutinin ha1 peptide chain,NaN,MH2,...,NaN,True,QSVTQLGSHVSVSEGALVLLRCNYSSSVPPYLFWYVQYPNQGLQLL...,-QSVTQLGSHVSVSEGALVLLRCNYSSSV------PPYLFWYVQYP...,KVTQSSRYLVKRTGEKVFLECVQDMDHENMFWYRQDPGLGLRLIYF...,--KVTQSSRYLVKRTGEKVFLECVQDMDH-------ENMFWYRQDP...,PKYVKQNTLKLAT,True,QSVTQLGSHVSVSEGALVLLRCNYSSSVPPYLFWYVQYPNQGLQLL...,KVTQSSRYLVKRTGEKVFLECVQDMDHENMFWYRQDPGLGLRLIYF...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,8cx4,F,D,abTCR,0,C,peptide,yeih,NaN,MH1,...,NaN,True,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSA------IYNLQWFRQDP...,DSGVTQTPKHLITATGQRVTLRCSPRSGDLSVYWYQQSLDQGLQFL...,DSGVTQTPKHLITATGQRVTLRCSPRSGD-------LSVYWYQQSL...,LRVMMLAPF,True,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,DSGVTQTPKHLITATGQRVTLRCSPRSGDLSVYWYQQSLDQGLQFL...
0,8d5p,D,C,abTCR,0,NaN,NaN,NaN,NaN,NaN,...,NaN,True,MDSVTQTEGQVALSEEDFLTIHCNYSASGYPALFWYVQYPGEGPQF...,MDSVTQTEGQVALSEEDFLTIHCNYSASG------YPALFWYVQYP...,MTLLEQNPRWRLVPRGQAVNLRCILKNSQYPWMSWYQQDLQKQLQW...,MTLLEQNPRWRLVPRGQAVNLRCILKNSQ------YPWMSWYQQDL...,NaN,False,MDSVTQTEGQVALSEEDFLTIHCNYSASGYPALFWYVQYPGEGPQF...,MTLLEQNPRWRLVPRGQAVNLRCILKNSQYPWMSWYQQDLQKQLQW...
0,8gvb,B,A,abTCR,0,P,peptide,8-mer peptide from protein nef,NaN,MH1,...,NaN,True,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGA------TPYLFWYVQSP...,DTGVSQDPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,DTGVSQDPRHKITKRGQNVTFRCDPISEH-------NRLYWYRQTL...,RYPLTFGW,True,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQDPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...
0,8gvg,B,A,abTCR,0,P,peptide,mutated 8-mer peptide from protein nef,NaN,MH1,...,NaN,True,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGA------TPYLFWYVQSP...,DTGVSQDPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,DTGVSQDPRHKITKRGQNVTFRCDPISEH-------NRLYWYRQTL...,RFPLTFGW,True,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQDPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...
0,8gvi,B,A,abTCR,0,P,peptide,8-mer peptide from protein nef,NaN,MH1,...,NaN,True,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGA------TPYLFWYVQSP...,DTGVSQDPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,DTGVSQDPRHKITKRGQNVTFRCDPISEH-------NRLYWYRQTL...,RYPLTFGW,True,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQDPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...

In [13]:
tcrdb['cdr3a'] = [a[103:118] for a in tcrdb['alpha_aa_imgt_withGaps']]
tcrdb['cdr3b'] = [b[103:118] for b in tcrdb['beta_aa_imgt_withGaps']]

In [14]:
tcrdb[['cdr3a', 'cdr3b', 'epitope_aa']]

              cdr3a            cdr3b        epitope_aa
0   CAVTTDS--WGKLQF  CASRPGLAGGRPEQY         LLFGYPVYV
0   CAAMEG---AQKLVF  CASSYPGGGFYEQYF         LLFGYPVYV
0   CAATGS---FNKLTF  CASGGQG--RAEQFF  GNSHRGAIEWEGIESG
0   CAMRGDYGGSGNKLI  CTCSADR-VGNTLYF          INFDFNTI
0   CAVSESPFGNEKLTF  CASSSTG-LPYGYTF     PKYVKQNTLKLAT
..              ...              ...               ...
0   CAVNSPGSGAGSYQL  CASSVGTYSTDTQYF         LRVMMLAPF
0   CALGDPTGANTGKLT  CTCSAGRGGYAEQFF               NaN
0   CAVGFTG-GGNKLTF  CASSDRDRVPETQYF          RYPLTFGW
0   CAVGFTG-GGNKLTF  CASSDRDRVPETQYF          RFPLTFGW
0   CAVVFTG-GGNKLTF  CASSLRDRVPETQYF          RYPLTFGW

[340 rows x 3 columns]

In [15]:
tcrdb.loc[tcrdb['pdb'] == '5euo']

,pdb,Bchain,Achain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,...,alpha_aa_imgt,alpha_aa_imgt_withGaps,beta_aa_imgt,beta_aa_imgt_withGaps,epitope_aa,bound,alpha_aa_imgt_shorter,beta_aa_imgt_shorter,cdr3a,cdr3b
0,5euo,H,G,abTCR,0,I,peptide,matrix protein 1,NaN,MH1,...,TQLLEQSPQFLSIQEGENLTVYCNSSSVFSSLQWYRQEPGEGPVLL...,TQLLEQSPQFLSIQEGENLTVYCNSSSVF-------SSLQWYRQEP...,GITQSPKYLFRKEGQNVTLSCEQNLNHDAMYWYRQDPGQGLRLIYY...,--GITQSPKYLFRKEGQNVTLSCEQNLNH-------DAMYWYRQDP...,GILGFVFTL,True,TQLLEQSPQFLSIQEGENLTVYCNSSSVFSSLQWYRQEPGEGPVLL...,GITQSPKYLFRKEGQNVTLSCEQNLNHDAMYWYRQDPGQGLRLIYY...,CAGAIGPSNTGKLIF,CASSIRS--SYEQYF

In [16]:
vdjdb.loc[vdjdb['CDR3-a'] == 'CAGAIGPSNTGKLIF']

Empty DataFrame
Columns: [Unnamed: 0, complex.id, Gene-a, CDR3-a, V-a, J-a, Species, MHC A, MHC B, MHC class, Epitope, Epitope gene, Epitope species, Reference, Method, Meta, CDR3fix-a, Score, Gene-b, CDR3-b, V-b, J-b, CDR3fix-b, TCRa, TCRb, cdr1a_IMGTgaps, cdr1b_IMGTgaps, cdr2a_IMGTgaps, cdr2b_IMGTgaps, cdr3a_IMGTgaps, cdr3b_IMGTgaps, len_cdr3a, len_cdr3b, len_cdr3a_IMGTgaps, cdr3a_IMGTgaps_padded, len_cdr3b_IMGTgaps, cdr3b_IMGTgaps_padded, structure]
Index: []

[0 rows x 38 columns]

In [17]:
vdjdb.loc[vdjdb['structure'] == '5EUO']

,Unnamed: 0,complex.id,Gene-a,CDR3-a,V-a,J-a,Species,MHC A,MHC B,MHC class,...,cdr2b_IMGTgaps,cdr3a_IMGTgaps,cdr3b_IMGTgaps,len_cdr3a,len_cdr3b,len_cdr3a_IMGTgaps,cdr3a_IMGTgaps_padded,len_cdr3b_IMGTgaps,cdr3b_IMGTgaps_padded,structure
473,1060,1077,TRA,CAGAIGSSNTGKLIF,TRAV27,TRAJ37,HomoSapiens,HLA-A*02,B2M,MHCI,...,SQI----VND,CAGAIGSSNTGKLIF,CASSIRS--SYEQYF,15,15,15,"C, A, G, A, I, G, S, S, -, -, -, -, N, T, G, K...",15,"C, A, S, S, I, R, S, -, -, -, -, -, -, S, Y, E...",5EUO

In [18]:
vdjdb_tcrs = list(zip(vdjdb['CDR3-a'], vdjdb['CDR3-b']))
vdjdb_complexes = list(zip(vdjdb['CDR3-a'], vdjdb['CDR3-b'], vdjdb['Epitope']))

In [19]:
tcrdb['tcr_in_vdj_set'] = [
    (a.replace('-',''), b.replace('-','')) in vdjdb_tcrs for a,b in zip(tcrdb['cdr3a'], tcrdb['cdr3b'])
]
tcrdb['complex_in_vdj_set'] = [
    (a.replace('-',''), b.replace('-',''), e) in vdjdb_tcrs for a,b,e in zip(tcrdb['cdr3a'], tcrdb['cdr3b'], tcrdb['epitope_aa'])
]

In [20]:
tcrdb['tcr_in_vdj_set'].value_counts()

False    336
True       4
Name: tcr_in_vdj_set, dtype: int64

In [21]:
tcrdb['complex_in_vdj_set'].value_counts()
# note this is because there was an error in the CDR3a of 5euo in VDJdb which I have reported and has since been fixed https://github.com/antigenomics/vdjdb-db/issues/360

False    340
Name: complex_in_vdj_set, dtype: int64