In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys

sys.path.insert(0, '..')
from PairingVDJdb_MI import _define_individuals
import functions.myfunctions as mf
import tidytcells as tt

In [2]:
vdj = pd.read_csv('../data/vdj_cleaned_subset_for_MI.csv', index_col = 0)
vdj = vdj.loc[vdj['Epitope'] != 'KLGGALQAK'] # because too big - takes forever
vdj = mf.prepare_data(vdj, col1 = 'cdr3a_IMGTgaps', col2='cdr3b_IMGTgaps', type = 'cdr3')
print(vdj.shape)

for c in ['V-a', 'V-b', 'J-a', 'J-b']:
    print(c)
    vdj[c] = vdj.apply(
        lambda row: pd.NA if type(row[c]) != str else tt.tcr.standardise(
            gene_name=row[c],
            species=row['Species'],
            precision='gene'
        ),
        axis=1
    )
vdj00 = vdj.dropna(subset=['V-a', 'V-b', 'J-a', 'J-b'])
print('shape before tidytcells: ', vdj.shape, '; shape after tidytcells: ', vdj00.shape)

vdj = vdj00.copy()

(9785, 37)
V-a
V-b
J-a
J-b
shape before tidytcells:  (9785, 37) ; shape after tidytcells:  (9785, 37)

In [3]:
vdj = vdj.reset_index(drop=True).reset_index(names = ['original_pair_index'])

In [4]:
vdj

,original_pair_index,Unnamed: 0,complex.id,Gene-a,CDR3-a,V-a,J-a,Species,MHC A,MHC B,...,cdr2a_IMGTgaps,cdr2b_IMGTgaps,cdr3a_IMGTgaps,cdr3b_IMGTgaps,len_cdr3a,len_cdr3b,len_cdr3a_IMGTgaps,cdr3a_IMGTgaps_padded,len_cdr3b_IMGTgaps,cdr3b_IMGTgaps_padded
0,0,13,14,TRA,CAYTVLGNEKLTF,TRAV38-1,TRAJ48,HomoSapiens,HLA-A*02,B2M,...,QEAY--KQQN,SYD----VKM,CAYTVLG--NEKLTF,CASSFTP--YNEQFF,15,15,15,"C, A, Y, T, V, L, G, -, -, -, -, -, -, N, E, K...",15,"C, A, S, S, F, T, P, -, -, -, -, -, -, Y, N, E..."
1,1,14,15,TRA,CAVAGYGGSQGNLIF,TRAV12-2,TRAJ42,HomoSapiens,HLA-A*02,B2M,...,IYS----NGD,SYD----VKM,CAVAGYGGSQGNLIF,CASSPQG-LGTEAFF,15,15,15,"C, A, V, A, G, Y, G, G, -, -, -, -, S, Q, G, N...",15,"C, A, S, S, P, Q, G, -, -, -, -, -, L, G, T, E..."
2,2,15,16,TRA,CAVSFGNEKLTF,TRAV12-2,TRAJ48,HomoSapiens,HLA-A*02,B2M,...,IYS----NGD,SYD----VKM,CAVSFG---NEKLTF,CAEGQGF-VGQPQHF,15,15,15,"C, A, V, S, F, G, -, -, -, -, -, -, -, N, E, K...",15,"C, A, E, G, Q, G, F, -, -, -, -, -, V, G, Q, P..."
3,3,16,17,TRA,CAVTHYGGSQGNLIF,TRAV12-2,TRAJ42,HomoSapiens,HLA-A*02,B2M,...,IYS----NGD,SYD----VKM,CAVTHYGGSQGNLIF,CASLRSAVWADTQYF,15,15,15,"C, A, V, T, H, Y, G, G, -, -, -, -, S, Q, G, N...",15,"C, A, S, L, R, S, A, V, -, -, -, -, W, A, D, T..."
4,4,17,18,TRA,CAGGGGGADGLTF,TRAV12-2,TRAJ45,HomoSapiens,HLA-A*02,B2M,...,IYS----NGD,SYD----VKM,CAGGGGG--ADGLTF,CASTLTG-LGQPQHF,15,15,15,"C, A, G, G, G, G, G, -, -, -, -, -, -, A, D, G...",15,"C, A, S, T, L, T, G, -, -, -, -, -, L, G, Q, P..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9780,9780,28936,29239,TRA,CAVMRGTALIF,TRAV8-4,TRAJ15,HomoSapiens,HLA-B*07:02,B2M,...,YTSA--ATLV,ANQG---SEA,CAVMRG----TALIF,CSVVGTG-GPETQYF,15,15,15,"C, A, V, M, R, G, -, -, -, -, -, -, -, -, T, A...",15,"C, S, V, V, G, T, G, -, -, -, -, -, G, P, E, T..."
9781,9781,28937,29240,TRA,CAVPTYSSASKIIF,TRAV8-4,TRAJ3,HomoSapiens,HLA-B*07:02,B2M,...,YTSA--ATLV,FQG----NSA,CAVPTYS-SASKIIF,CASSSG---GYEQYF,15,15,15,"C, A, V, P, T, Y, S, -, -, -, -, -, S, A, S, K...",15,"C, A, S, S, S, G, -, -, -, -, -, -, -, G, Y, E..."
9782,9782,28938,29241,TRA,CALSATSGTYKYIF,TRAV9-2,TRAJ40,HomoSapiens,HLA-B*07:02,B2M,...,ATKA---DDK,SMN----VEV,CALSATS-GTYKYIF,CASSPLSGTSATKETQYF,15,18,15,"C, A, L, S, A, T, S, -, -, -, -, -, G, T, Y, K...",18,"C, A, S, S, P, L, S, G, T, -, S, A, T, K, E, T..."
9783,9783,28939,29242,TRA,CAALAGTASKLTF,TRAV13-1,TRAJ44,HomoSapiens,HLA-B*07:02,B2M,...,IRSN---VGE,ANQG---SEA,CAALAGT--ASKLTF,CSVVPLA-GPYEQYF,15,15,15,"C, A, A, L, A, G, T, -, -, -, -, -, -, A, S, K...",15,"C, S, V, V, P, L, A, -, -, -, -, -, G, P, Y, E..."
9784,9784,28940,29243,TRA,CADPNTGNQFYF,TRAV13-2,TRAJ49,HomoSapiens,HLA-B*07:02,B2M,...,IRSN---MDK,FNY----EAQ,CADPNT---GNQFYF,CASSRRWGSSYEQYF,15,15,15,"C, A, D, P, N, T, -, -, -, -, -, -, -, G, N, Q...",15,"C, A, S, S, R, R, W, G, -, -, -, -, S, S, Y, E..."

In [5]:
known_binders = []

for ep in vdj['Epitope'].unique():
   known_binders.append(_define_individuals(vdj, ep, ind = 'no'))

known_binders

Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided
Using individuals as provided

[     original_pair_index  complex.id Gene-a           CDR3-a       V-a  \
 0                   2449        4976    TRA  CAVNTSGGGADGLTF  TRAV12-2
 1                   2361        4763    TRA    CAVPGSTGNQFYF  TRAV12-2
 2                   2366        4783    TRA   CALGGYSSASKIIF  TRAV12-2
 3                   2367        4785    TRA   CAVNIETGANNLFF  TRAV12-2
 4                   2382        4821    TRA    CAVNGGGADGLTF  TRAV12-2
 ..                   ...         ...    ...              ...       ...
 375                 9219       26663    TRA     CAVGGGADGLTF  TRAV12-2
 376                   45         159    TRA     CAVNFGGGKLIF  TRAV12-2
 377                   46         161    TRA      CAGGTGNQFYF    TRAV35
 378                   47         184    TRA     CAVNFGGGKLIF  TRAV12-2
 379                   51         257    TRA    CAVTKYSWGKLQF  TRAV12-2

         J-a      Species           MHC A MHC B MHC class  ...  \
 0    TRAJ45  HomoSapiens     HLA-A*02:01   B2M      MHCI  ...
 1    TRAJ49  HomoSapiens     HLA-A*02:01   B2M      MHCI  ...
 2     TRAJ3  HomoSapiens     HLA-A*02:01   B2M      MHCI  ...
 3    TRAJ36  HomoSapiens     HLA-A*02:01   B2M      MHCI  ...
 4    TRAJ45  HomoSapiens     HLA-A*02:01   B2M      MHCI  ...
 ..      ...          ...             ...   ...       ...  ...
 375  TRAJ45  HomoSapiens     HLA-A*02:01   B2M      MHCI  ...
 376  TRAJ23  HomoSapiens  HLA-A*02:01:48   B2M      MHCI  ...
 377  TRAJ49  HomoSapiens  HLA-A*02:01:48   B2M      MHCI  ...
 378  TRAJ23  HomoSapiens  HLA-A*02:01:48   B2M      MHCI  ...
 379  TRAJ24  HomoSapiens  HLA-A*02:01:48   B2M      MHCI  ...

       cdr3a_IMGTgaps     cdr3b_IMGTgaps len_cdr3a len_cdr3b  \
 0    CAVNTSGGGADGLTF  CASSQDLLAGAADTQYF        15        17
 1    CAVPGST--GNQFYF    CASSFGF--GQPQHF        15        15
 2    CALGGYS-SASKIIF    CASTTTGTSSYEQYF        15        15
 3    CAVNIET-GANNLFF    CASRPTG-LGQPQHF        15        15
 4    CAVNGGG--ADGLTF    CASSPGVLASNEQFF        15        15
 ..               ...                ...       ...       ...
 375  CAVGGG---ADGLTF   CASSPAALSGAYEQYF        15        16
 376  CAVNFG---GGKLIF    CASSLSF--GTEAFF        15        15
 377  CAGGTG----NQFYF    CAISEVG-VGQPQHF        15        15
 378  CAVNFG---GGKLIF    CASSWSF--GTEAFF        15        15
 379  CAVTKYS--WGKLQF   CASRPGWMAGGVELYF        15        16

     len_cdr3a_IMGTgaps                              cdr3a_IMGTgaps_padded  \
 0                   15  C, A, V, N, T, S, G, G, -, -, -, -, G, A, D, G...
 1                   15  C, A, V, P, G, S, T, -, -, -, -, -, -, G, N, Q...
 2                   15  C, A, L, G, G, Y, S, -, -, -, -, -, S, A, S, K...
 3                   15  C, A, V, N, I, E, T, -, -, -, -, -, G, A, N, N...
 4                   15  C, A, V, N, G, G, G, -, -, -, -, -, -, A, D, G...
 ..                 ...                                                ...
 375                 15  C, A, V, G, G, G, -, -, -, -, -, -, -, A, D, G...
 376                 15  C, A, V, N, F, G, -, -, -, -, -, -, -, G, G, K...
 377                 15  C, A, G, G, T, G, -, -, -, -, -, -, -, -, N, Q...
 378                 15  C, A, V, N, F, G, -, -, -, -, -, -, -, G, G, K...
 379                 15  C, A, V, T, K, Y, S, -, -, -, -, -, -, W, G, K...

     len_cdr3b_IMGTgaps                              cdr3b_IMGTgaps_padded  \
 0                   17  C, A, S, S, Q, D, L, L, -, -, A, G, A, A, D, T...
 1                   15  C, A, S, S, F, G, F, -, -, -, -, -, -, G, Q, P...
 2                   15  C, A, S, T, T, T, G, T, -, -, -, -, S, S, Y, E...
 3                   15  C, A, S, R, P, T, G, -, -, -, -, -, L, G, Q, P...
 4                   15  C, A, S, S, P, G, V, L, -, -, -, -, A, S, N, E...
 ..                 ...                                                ...
 375                 16  C, A, S, S, P, A, A, L, -, -, -, S, G, A, Y, E...
 376                 15  C, A, S, S, L, S, F, -, -, -, -, -, -, G, T, E...
 377                 15  C, A, I, S, E, V, G, -, -, -, -, -, V, G, Q, P...
 378                 15  C, A, S, S, W, S, F, -, -, -, -, -, -, G, T, E...
 379                 16  C, A, S, R, P, G, W, M, -, -, -, A, G, G, V, E...

     subject_id           subject-PMID
 0            1          10xGenomics_1
 1            1          10xGenomics_1
 2            1          10xGenomics_1
 3            1          10xGenomics_1
 4            1          10xGenomics_1
 ..         ...                    ...
 375       None  PMID:19786555_unknown
 376       None  PMID:21795600_unknown
 377       None  PMID:21795600_unknown
 378       None  PMID:24550723_unknown
 379       None  PMID:27238970_unknown

 [380 rows x 39 columns],
       original_pair_index  complex.id Gene-a             CDR3-a       V-a  \
 0                    2457        4994    TRA     CVVNGLGGYSTLTF  TRAV12-1
 1                    1859        3653    TRA    CAGAAGSSNTGKLIF    TRAV27
 2                    1860        3654    TRA       CAGGGSQGNLIF    TRAV27
 3                    1863        3657    TRA  CAFMINAGGTSYGKLTF  TRAV38-1
 4                    1867        3663    TRA       CADMNRDDKIIF  TRAV13-2
 ...                   ...         ...    ...                ...       ...
 1889                 9478       27547    TRA  CVVNKSHRGSTLGRLYF  TRAV12-1
 1890                 9538       27621    TRA     CAVGNGGSQGNLIF   TRAV1-2
 1891                   64         369    TRA       CAGGGSQGNLIF    TRAV27
 1892                   63         368    TRA    CAVNSYYNQGGKLIF  TRAV12-2
 1893                   62         366    TRA      CAGATGNTGKLIF    TRAV27

          J-a      Species        MHC A MHC B MHC class  ...  \
 0     TRAJ11  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 1     TRAJ37  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 2     TRAJ42  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 3     TRAJ52  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 4     TRAJ30  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 ...      ...          ...          ...   ...       ...  ...
 1889  TRAJ18  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 1890  TRAJ42  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 1891  TRAJ42  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 1892  TRAJ23  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...
 1893  TRAJ37  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...

          cdr3a_IMGTgaps    cdr3b_IMGTgaps len_cdr3a len_cdr3b  \
 0       CVVNGLG-GYSTLTF   CASSIRA--SYEQYF        15        15
 1       CAGAAGSSNTGKLIF   CASSIRS--SYEQYF        15        15
 2       CAGGGS---QGNLIF   CSASAPT--SYEQYF        15        15
 3     CAFMINAGGTSYGKLTF   CASSDSY-LEGGYTF        17        15
 4       CADMNR---DDKIIF   CASSLEW-GGETQYF        15        15
 ...                 ...               ...       ...       ...
 1889  CVVNKSHRGSTLGRLYF   CASSFYS--TTEQFF        17        15
 1890    CAVGNGG-SQGNLIF  CASSQDPAGGGVEQFF        15        16
 1891    CAGGGS---QGNLIF   CASSIRS--SYEQYF        15        15
 1892    CAVNSYYNQGGKLIF   CSVLQGS--PYEQYF        15        15
 1893    CAGATGN--TGKLIF   CASSTRG--AYEQYF        15        15

      len_cdr3a_IMGTgaps                              cdr3a_IMGTgaps_padded  \
 0                    15  C, V, V, N, G, L, G, -, -, -, -, -, G, Y, S, T...
 1                    15  C, A, G, A, A, G, S, S, -, -, -, -, N, T, G, K...
 2                    15  C, A, G, G, G, S, -, -, -, -, -, -, -, Q, G, N...
 3                    17  C, A, F, M, I, N, A, G, -, -, G, T, S, Y, G, K...
 4                    15  C, A, D, M, N, R, -, -, -, -, -, -, -, D, D, K...
 ...                 ...                                                ...
 1889                 17  C, V, V, N, K, S, H, R, -, -, G, S, T, L, G, R...
 1890                 15  C, A, V, G, N, G, G, -, -, -, -, -, S, Q, G, N...
 1891                 15  C, A, G, G, G, S, -, -, -, -, -, -, -, Q, G, N...
 1892                 15  C, A, V, N, S, Y, Y, N, -, -, -, -, Q, G, G, K...
 1893                 15  C, A, G, A, T, G, N, -, -, -, -, -, -, T, G, K...

      len_cdr3b_IMGTgaps                              cdr3b_IMGTgaps_padded  \
 0                    15  C, A, S, S, I, R, A, -, -, -, -, -, -, S, Y, E...
 1                    15  C, A, S, S, I, R, S, -, -, -, -, -, -, S, Y, E...
 2                    15  C, S, A, S, A, P, T, -, -, -, -, -, -, S, Y, E...
 3                    15  C, A, S, S, D, S, Y, -, -, -, -, -, L, E, G, G...
 4                    15  C, A, S, S, L, E, W, -, -, -, -, -, G, G, E, T...
 ...                 ...                                                ...
 1889                 15  C, A, S, S, F, Y, S, -, -, -, -, -, -, T, T, E...
 1890                 16  C, A, S, S, Q, D, P, A, -, -, -, G, G, G, V, E...
 1891                 15  C, A, S, S, I, R, S, -, -, -, -, -, -, S, Y, E...
 1892                 15  C, S, V, L, Q, G, S, -, -, -, -, -, -, P, Y, E...
 1893                 15  C, A, S, S, T, R, G, -, -, -, -, -, -, A, Y, E...

      subject_id           subject-PMID
 0             1          10xGenomics_1
 1             1          10xGenomics_1
 2             1          10xGenomics_1
 3             1          10xGenomics_1
 4             1          10xGenomics_1
 ...         ...                    ...
 1889       None  PMID:34793243_unknown
 1890       None  PMID:34793243_unknown
 1891       None   PMID:7807026_unknown
 1892       None   PMID:7807026_unknown
 1893       None   PMID:7807026_unknown

 [1894 rows x 39 columns],
      original_pair_index  complex.id Gene-a            CDR3-a         V-a  \
 0                   5424       12372    TRA     CAVWMDSSYKLIF     TRAV1-2
 1                   6769       22389    TRA      CADLQTNARLMF       TRAV5
 2                   9231       26723    TRA    CAGPMKTSYDKVIF      TRAV35
 3                   9230       26721    TRA       CATNTGNQFYF      TRAV24
 4                   9229       26720    TRA      CAARANNARLMF  TRAV29/DV5
 ..                   ...         ...    ...               ...         ...
 352                  213         815    TRA      CAWMNRDDKIIF      TRAV24
 353                  214         816    TRA  CAGKSLFGTNAGKSTF      TRAV25
 354                  215         817    TRA   CIVRPRWDSNYQLIW    TRAV26-1
 355                  193         793    TRA      CAVRDISARLMF       TRAV3
 356                  240         846    TRA    CAVPPQGGSEKLVF     TRAV8-3

         J-a      Species        MHC A MHC B MHC class  ...    cdr3a_IMGTgaps  \
 0    TRAJ12  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CAVWMDS--SYKLIF
 1    TRAJ31  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CADLQT---NARLMF
 2    TRAJ50  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CAGPMKT-SYDKVIF
 3    TRAJ49  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CATNTG----NQFYF
 4    TRAJ31  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CAARAN---NARLMF
 ..      ...          ...          ...   ...       ...  ...               ...
 352  TRAJ30  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CAWMNR---DDKIIF
 353  TRAJ27  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAGKSLFGTNAGKSTF
 354  TRAJ33  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CIVRPRWDSNYQLIW
 355  TRAJ31  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CAVRDI---SARLMF
 356  TRAJ57  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...   CAVPPQG-GSEKLVF

        cdr3b_IMGTgaps len_cdr3a len_cdr3b len_cdr3a_IMGTgaps  \
 0     CASSQEAADNEKLFF        15        15                 15
 1     CSGGQGM--VDGYTF        15        15                 15
 2     CASSSA---NYGYTF        15        15                 15
 3     CASSPQTGTIYGYTF        15        15                 15
 4    CASSLEYSPRPYEQYF        15        16                 15
 ..                ...       ...       ...                ...
 352   CASSVVG--YLGYTF        15        15                 15
 353  CASSRGQGPGQETQYF        16        16                 16
 354  CASSQAPSMEPNEQFF        15        16                 15
 355   CASSSV----NVAFF        15        15                 15
 356   CASFSPR--VYEQYF        15        15                 15

                                  cdr3a_IMGTgaps_padded len_cdr3b_IMGTgaps  \
 0    C, A, V, W, M, D, S, -, -, -, -, -, -, S, Y, K...                 15
 1    C, A, D, L, Q, T, -, -, -, -, -, -, -, N, A, R...                 15
 2    C, A, G, P, M, K, T, -, -, -, -, -, S, Y, D, K...                 15
 3    C, A, T, N, T, G, -, -, -, -, -, -, -, -, N, Q...                 15
 4    C, A, A, R, A, N, -, -, -, -, -, -, -, N, A, R...                 16
 ..                                                 ...                ...
 352  C, A, W, M, N, R, -, -, -, -, -, -, -, D, D, K...                 15
 353  C, A, G, K, S, L, F, G, -, -, -, T, N, A, G, K...                 16
 354  C, I, V, R, P, R, W, D, -, -, -, -, S, N, Y, Q...                 16
 355  C, A, V, R, D, I, -, -, -, -, -, -, -, S, A, R...                 15
 356  C, A, V, P, P, Q, G, -, -, -, -, -, G, S, E, K...                 15

                                  cdr3b_IMGTgaps_padded subject_id  \
 0    C, A, S, S, Q, E, A, A, -, -, -, -, D, N, E, K...          3
 1    C, S, G, G, Q, G, M, -, -, -, -, -, -, V, D, G...          4
 2    C, A, S, S, S, A, -, -, -, -, -, -, -, N, Y, G...       efim
 3    C, A, S, S, P, Q, T, G, -, -, -, -, T, I, Y, G...       filk
 4    C, A, S, S, L, E, Y, S, -, -, -, P, R, P, Y, E...       kond
 ..                                                 ...        ...
 352  C, A, S, S, V, V, G, -, -, -, -, -, -, Y, L, G...      R3000
 353  C, A, S, S, R, G, Q, G, -, -, -, P, G, Q, E, T...      R3000
 354  C, A, S, S, Q, A, P, S, -, -, -, M, E, P, N, E...      R3000
 355  C, A, S, S, S, V, -, -, -, -, -, -, -, -, N, V...      R3000
 356  C, A, S, F, S, P, R, -, -, -, -, -, -, V, Y, E...      R3000

                                           subject-PMID
 0                                        10xGenomics_3
 1                                        10xGenomics_4
 2                                  GitHubIssue252_efim
 3                                  GitHubIssue252_filk
 4                                  GitHubIssue252_kond
 ..                                                 ...
 352  https://doi.org/10.1101/2020.05.04.20085779_R3000
 353  https://doi.org/10.1101/2020.05.04.20085779_R3000
 354  https://doi.org/10.1101/2020.05.04.20085779_R3000
 355  https://doi.org/10.1101/2020.05.04.20085779_R3000
 356  https://doi.org/10.1101/2020.05.04.20085779_R3000

 [357 rows x 39 columns],
      original_pair_index  complex.id Gene-a           CDR3-a       V-a  \
 0                   2876        6087    TRA    CGTEYPNDYKLSF    TRAV30
 1                   1600        3141    TRA     CAEYSSASKIIF     TRAV5
 2                   1648        3224    TRA    CAVSENRDDKIIF   TRAV8-4
 3                   1684        3296    TRA      CAEAGANNLFF     TRAV5
 4                   1697        3324    TRA  CAVRGPEGGGNKLTF   TRAV1-2
 ..                   ...         ...    ...              ...       ...
 340                 9395       27395    TRA      CAEDKDSTLTF     TRAV5
 341                 9394       27394    TRA      CAEDANARLMF     TRAV5
 342                 9400       27402    TRA   CALSSNQAGTALIF    TRAV16
 343                  455        1101    TRA     CAESTSGGKLIF     TRAV5
 344                  456        1102    TRA   CVVNGKDSSYKLIF  TRAV12-1

         J-a      Species        MHC A MHC B MHC class  ...   cdr3a_IMGTgaps  \
 0    TRAJ20  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CGTEYPN--DYKLSF
 1     TRAJ3  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAEYSS---ASKIIF
 2    TRAJ30  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAVSENR--DDKIIF
 3    TRAJ36  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAEAGA----NNLFF
 4    TRAJ10  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAVRGPEGGGNKLTF
 ..      ...          ...          ...   ...       ...  ...              ...
 340  TRAJ11  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAEDKD----STLTF
 341  TRAJ31  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAEDAN----ARLMF
 342  TRAJ15  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CALSSNQ-AGTALIF
 343  TRAJ37  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CAESTS---GGKLIF
 344  TRAJ12  HomoSapiens  HLA-A*02:01   B2M      MHCI  ...  CVVNGKD-SSYKLIF

       cdr3b_IMGTgaps len_cdr3a len_cdr3b len_cdr3a_IMGTgaps  \
 0    CATSTGD-SNQPQHF        15        15                 15
 1    CASSQSP--GGTQYF        15        15                 15
 2    CSARDST--GNGYTF        15        15                 15
 3    CASSQSP--GGTQYF        15        15                 15
 4    CASSAGTSGQETQYF        15        15                 15
 ..               ...       ...       ...                ...
 340  CSARDST--GNGYTF        15        15                 15
 341  CSARSHV--GNTIYF        15        15                 15
 342  CASSVDSGLTGELFF        15        15                 15
 343  CSVGTGG-TNEKLFF        15        15                 15
 344  CASSGGAVAPSEQFF        15        15                 15

                                  cdr3a_IMGTgaps_padded len_cdr3b_IMGTgaps  \
 0    C, G, T, E, Y, P, N, -, -, -, -, -, -, D, Y, K...                 15
 1    C, A, E, Y, S, S, -, -, -, -, -, -, -, A, S, K...                 15
 2    C, A, V, S, E, N, R, -, -, -, -, -, -, D, D, K...                 15
 3    C, A, E, A, G, A, -, -, -, -, -, -, -, -, N, N...                 15
 4    C, A, V, R, G, P, E, G, -, -, -, -, G, G, N, K...                 15
 ..                                                 ...                ...
 340  C, A, E, D, K, D, -, -, -, -, -, -, -, -, S, T...                 15
 341  C, A, E, D, A, N, -, -, -, -, -, -, -, -, A, R...                 15
 342  C, A, L, S, S, N, Q, -, -, -, -, -, A, G, T, A...                 15
 343  C, A, E, S, T, S, -, -, -, -, -, -, -, G, G, K...                 15
 344  C, V, V, N, G, K, D, -, -, -, -, -, S, S, Y, K...                 15

                                  cdr3b_IMGTgaps_padded subject_id  \
 0    C, A, T, S, T, G, D, -, -, -, -, -, S, N, Q, P...          1
 1    C, A, S, S, Q, S, P, -, -, -, -, -, -, G, G, T...          1
 2    C, S, A, R, D, S, T, -, -, -, -, -, -, G, N, G...          1
 3    C, A, S, S, Q, S, P, -, -, -, -, -, -, G, G, T...          1
 4    C, A, S, S, A, G, T, S, -, -, -, -, G, Q, E, T...          1
 ..                                                 ...        ...
 340  C, S, A, R, D, S, T, -, -, -, -, -, -, G, N, G...       None
 341  C, S, A, R, S, H, V, -, -, -, -, -, -, G, N, T...       None
 342  C, A, S, S, V, D, S, G, -, -, -, -, L, T, G, E...       None
 343  C, S, V, G, T, G, G, -, -, -, -, -, T, N, E, K...       None
 344  C, A, S, S, G, G, A, V, -, -, -, -, A, P, S, E...       None

               subject-PMID
 0            10xGenomics_1
 1            10xGenomics_1
 2            10xGenomics_1
 3            10xGenomics_1
 4            10xGenomics_1
 ..                     ...
 340  PMID:34793243_unknown
 341  PMID:34793243_unknown
 342  PMID:34793243_unknown
 343  PMID:34811538_unknown
 344  PMID:34811538_unknown

 [345 rows x 39 columns],
      original_pair_index  complex.id Gene-a            CDR3-a          V-a  \
 0                     44         157    TRA     CILSGGSNYKLTF  TRAV21/DV12
 1                   7605       23785    TRA     CALGEGSNYQLIW      TRAV6-6
 2                   8006       24310    TRA   CAMRGVSGGNYKPTF       TRAV16
 3                   8472       25390    TRA     CAYSGGSNYKLTF     TRAV6D-6
 4                   7606       23786    TRA     CALGEGSNYQLIW      TRAV6-6
 ..                   ...         ...    ...               ...          ...
 345                 7797       24034    TRA     CALSGTNTNKVVF    TRAV12D-1
 346                 8548       25482    TRA     CVFSGGSNYKLTF     TRAV9N-2
 347                 7798       24035    TRA     CALSGTNTNKVVF    TRAV12D-1
 348                 8500       25420    TRA  CILRVGATGGNNKLTF  TRAV21/DV12
 349                 7735       23948    TRA   CALSDNTEGADRLTF  TRAV6-7/DV9


In [6]:
known_binders = pd.concat(known_binders)
assert known_binders.shape[0] == vdj.shape[0]

In [7]:
known_binders = known_binders[['original_pair_index', 'CDR3-a', 'CDR3-b', 'Epitope', 'MHC A', 'subject-PMID']]

In [8]:
known_binders['binder'] = 1

In [9]:
known_binders.head()

,original_pair_index,CDR3-a,CDR3-b,Epitope,MHC A,subject-PMID,binder
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1
1,2361,CAVPGSTGNQFYF,CASSFGFGQPQHF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1
2,2366,CALGGYSSASKIIF,CASTTTGTSSYEQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1
3,2367,CAVNIETGANNLFF,CASRPTGLGQPQHF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1
4,2382,CAVNGGGADGLTF,CASSPGVLASNEQFF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1

In [10]:
shuffled = known_binders.copy()

In [11]:
shuffled1 = []

for ep in shuffled['Epitope'].unique():
    s_ep = shuffled.loc[shuffled['Epitope'] == ep]
    for subj in s_ep['subject-PMID'].unique():
        s_ep_subj = s_ep.loc[s_ep['subject-PMID'] == subj]
        betas = s_ep_subj['CDR3-b'].unique().tolist()
        for a in s_ep_subj['CDR3-a'].unique():
            s_ep_subj_a = s_ep_subj.loc[s_ep_subj['CDR3-a'] == a]
            for b in betas:
                s_ep_subj_a1 = s_ep_subj_a.copy()
                s_ep_subj_a1['CDR3-b_shuffle'] = b
                shuffled1.append(s_ep_subj_a1)

In [12]:
shuffled1 = pd.concat(shuffled1)
shuffled1 = shuffled1.drop_duplicates()
shuffled1

,original_pair_index,CDR3-a,CDR3-b,Epitope,MHC A,subject-PMID,binder,CDR3-b_shuffle
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSQDLLAGAADTQYF
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSFGFGQPQHF
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASTTTGTSSYEQYF
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASRPTGLGQPQHF
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSPGVLASNEQFF
...,...,...,...,...,...,...,...,...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSLWNTGELFF
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CSATYRGTPYEQYF
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CATQPRSSYNSPLHF
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSLIAGGPEAKNIQYF
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSPLTGGPEEKGTQYF

In [13]:
shuffled1['pair_name'] = shuffled1['CDR3-a'] + '::' + shuffled1['CDR3-b_shuffle'] + '::' + shuffled1['subject-PMID']
shuffled1

,original_pair_index,CDR3-a,CDR3-b,Epitope,MHC A,subject-PMID,binder,CDR3-b_shuffle,pair_name
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSQDLLAGAADTQYF,CAVNTSGGGADGLTF::CASSQDLLAGAADTQYF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSFGFGQPQHF,CAVNTSGGGADGLTF::CASSFGFGQPQHF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASTTTGTSSYEQYF,CAVNTSGGGADGLTF::CASTTTGTSSYEQYF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASRPTGLGQPQHF,CAVNTSGGGADGLTF::CASRPTGLGQPQHF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSPGVLASNEQFF,CAVNTSGGGADGLTF::CASSPGVLASNEQFF::10xGenomics_1
...,...,...,...,...,...,...,...,...,...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSLWNTGELFF,CAVRNNARLMF::CASSLWNTGELFF::PMID:34793243_unknown
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CSATYRGTPYEQYF,CAVRNNARLMF::CSATYRGTPYEQYF::PMID:34793243_unk...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CATQPRSSYNSPLHF,CAVRNNARLMF::CATQPRSSYNSPLHF::PMID:34793243_un...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSLIAGGPEAKNIQYF,CAVRNNARLMF::CASSLIAGGPEAKNIQYF::PMID:34793243...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSPLTGGPEEKGTQYF,CAVRNNARLMF::CASSPLTGGPEEKGTQYF::PMID:34793243...

In [14]:
known_binders['pair_name'] = known_binders['CDR3-a'] + '::' + known_binders['CDR3-b'] + '::' + known_binders['subject-PMID']

In [15]:
shuffled1 = shuffled1.loc[~shuffled1['pair_name'].isin(known_binders['pair_name'])]
shuffled1

,original_pair_index,CDR3-a,CDR3-b,Epitope,MHC A,subject-PMID,binder,CDR3-b_shuffle,pair_name
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSFGFGQPQHF,CAVNTSGGGADGLTF::CASSFGFGQPQHF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASTTTGTSSYEQYF,CAVNTSGGGADGLTF::CASTTTGTSSYEQYF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASRPTGLGQPQHF,CAVNTSGGGADGLTF::CASRPTGLGQPQHF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSPGVLASNEQFF,CAVNTSGGGADGLTF::CASSPGVLASNEQFF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSQDLLAGAADTQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,1,CASSLEGQGGSPLHF,CAVNTSGGGADGLTF::CASSLEGQGGSPLHF::10xGenomics_1
...,...,...,...,...,...,...,...,...,...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASNLLTGGDADTQYF,CAVRNNARLMF::CASNLLTGGDADTQYF::PMID:34793243_u...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSLWNTGELFF,CAVRNNARLMF::CASSLWNTGELFF::PMID:34793243_unknown
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CSATYRGTPYEQYF,CAVRNNARLMF::CSATYRGTPYEQYF::PMID:34793243_unk...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CATQPRSSYNSPLHF,CAVRNNARLMF::CATQPRSSYNSPLHF::PMID:34793243_un...
174,9567,CAVRNNARLMF,CASSPLTGGPEEKGTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,1,CASSLIAGGPEAKNIQYF,CAVRNNARLMF::CASSLIAGGPEAKNIQYF::PMID:34793243...

In [16]:
shuffled1['binder'] = 0
shuffled1['CDR3-b'] = shuffled1['CDR3-b_shuffle']
shuffled1 = shuffled1.drop('CDR3-b_shuffle', axis=1)
shuffled1

/tmp/ipykernel_1809712/3928017036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shuffled1['binder'] = 0
/tmp/ipykernel_1809712/3928017036.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shuffled1['CDR3-b'] = shuffled1['CDR3-b_shuffle']

,original_pair_index,CDR3-a,CDR3-b,Epitope,MHC A,subject-PMID,binder,pair_name
0,2449,CAVNTSGGGADGLTF,CASSFGFGQPQHF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,0,CAVNTSGGGADGLTF::CASSFGFGQPQHF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASTTTGTSSYEQYF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,0,CAVNTSGGGADGLTF::CASTTTGTSSYEQYF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASRPTGLGQPQHF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,0,CAVNTSGGGADGLTF::CASRPTGLGQPQHF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSPGVLASNEQFF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,0,CAVNTSGGGADGLTF::CASSPGVLASNEQFF::10xGenomics_1
0,2449,CAVNTSGGGADGLTF,CASSLEGQGGSPLHF,ELAGIGILTV,HLA-A*02:01,10xGenomics_1,0,CAVNTSGGGADGLTF::CASSLEGQGGSPLHF::10xGenomics_1
...,...,...,...,...,...,...,...,...
174,9567,CAVRNNARLMF,CASNLLTGGDADTQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,0,CAVRNNARLMF::CASNLLTGGDADTQYF::PMID:34793243_u...
174,9567,CAVRNNARLMF,CASSLWNTGELFF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,0,CAVRNNARLMF::CASSLWNTGELFF::PMID:34793243_unknown
174,9567,CAVRNNARLMF,CSATYRGTPYEQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,0,CAVRNNARLMF::CSATYRGTPYEQYF::PMID:34793243_unk...
174,9567,CAVRNNARLMF,CATQPRSSYNSPLHF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,0,CAVRNNARLMF::CATQPRSSYNSPLHF::PMID:34793243_un...
174,9567,CAVRNNARLMF,CASSLIAGGPEAKNIQYF,SPRWYFYYL,HLA-B*07:02,PMID:34793243_unknown,0,CAVRNNARLMF::CASSLIAGGPEAKNIQYF::PMID:34793243...

In [17]:
all_pairs = pd.concat([known_binders, shuffled1])
all_pairs.to_csv('../data/output/benchmarking/benchmarking_pairs.csv.gz')